exParcial/exParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('wikiApp.urls'))
]

exParcial/wikiApp/urls.py
from django.urls import path, include
from . import views

app_name = 'wikiApp'

urlpatterns = [
    path('',views.directorio,name='directorio'),
    path('nuevoTema',views.nuevoTema,name='nuevoTema'),
    path('nuevoArticulo',views.nuevoArticulo, name='nuevoArticulo'),
    path('vistaArticulo/<str:idTema>',views.vistaArticulo,name='vistaArticulo'),
    path('vistaDetalleArticulo/<str:idArticulo>',views.vistaDetalleArticulo,name='vistaDetalleArticulo'),
]

exParcial/wikiApp/models.py
from django.db import models

# Create your models here.

class tema(models.Model):
    tituloTema = models.CharField(max_length=128, null=True, blank=True)
    descripcionTema = models.CharField(max_length=512, null=True, blank=True)

class articulo(models.Model):
    tituloArticulo = models.CharField(max_length=128, null=True, blank=True)
    contenidoArticulo = models.CharField(max_length=1024, null=True, blank=True)
    temaRelacionado = models.ForeignKey(tema, null=True,blank=True,on_delete=models.SET_NULL)

exParcial/wikiApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import tema, articulo

# Create your views here.
def directorio(request):
    listaTema = tema.objects.all().order_by('id')
    return render(request,'directorio.html',{
        'listaTema':listaTema
    })

def nuevoTema(request):
    listaTema = tema.objects.all().order_by('id')
    if request.method == 'POST':
        tituloTema = request.POST.get('tituloTema')
        descripcionTema = request.POST.get('descripcionTema')
        objTema = tema.objects.create(
            tituloTema = tituloTema,
            descripcionTema = descripcionTema
            )
        objTema.save()
        return HttpResponseRedirect(reverse('wikiApp:directorio'))
    return render(request,'nuevoTema.html',{
        'listaTema':listaTema
    })

def nuevoArticulo(request): 
    listaTema = tema.objects.all().order_by('id')
    if request.method == 'POST':
        tituloArticulo = request.POST.get('tituloArticulo')
        nombreTema = request.POST.get('nombreTema')
        contenidoArticulo = request.POST.get('contenidoArticulo')
        temaRelacionado = tema.objects.get(id=nombreTema)
        objArticulo = articulo.objects.create(
            tituloArticulo = tituloArticulo,
            contenidoArticulo = contenidoArticulo,
            temaRelacionado = temaRelacionado     
        )
        objArticulo.save()
    return render(request,'nuevoArticulo.html',{
        'listaTema':listaTema
    })

def vistaArticulo(request,idTema):
    listaTema = tema.objects.all().order_by('id')
    objTema = tema.objects.get(id=idTema)
    listaArticulo = objTema.articulo_set.all()
    return render(request,'vistaArticulo.html',{
        'listaTema':listaTema,
        'objTema':objTema,
        'listaArticulo': listaArticulo
    })

def vistaDetalleArticulo(request,idArticulo):
    listaTema = tema.objects.all().order_by('id')
    objArticulo = articulo.objects.get(id=idArticulo)
    return render(request,'vistaDetalleArticulo.html',{
        'listaTema':listaTema,
        'objArticulo':objArticulo, 
    })

exParcial/wikiApp/templates/directorio.html
{% extends "layout.html" %}

{% block title %}
    Directorio
{% endblock %}

block contenido %}
    {% for teaminfo in listaArticulo %}
        <div>
            <a href="{% url 'wikiApp:vistaDetalleArticulo' teaminfo.id %}">{{ teaminfo.tituloArticulo }}</a>            
        </div>
    {% endfor %}
{% endblock %}

exParcial/wikiApp/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Inclusion Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title%}{% endblock %}</title>
</head>
<body>
    <div class="row">
        <div class="col-lg-2">
            <h2>Directorio</h2>
            <form action="">
                <input type="text"class="form-control">
                <input type="submit" class="btb btn-success" value="Buscar">
            </form>
            <div class="container bg-info">
                <h5>Temas en tendencia</h5>
                {% for teaminfo in listaTema %}
                    <div>
                        <a href="{% url 'wikiApp:vistaArticulo' teaminfo.id %}">{{ teaminfo.tituloTema }}</a>
                    </div>
                {% endfor %}
            </div>
            <div>
                <a class="btn btn-outline-primary" href="{% url 'wikiApp:nuevoTema' %}" role="button">Crear nuevo Tema</a>                
            </div>
            <div>
                <a class="btn btn-outline-secondary" href="{% url 'wikiApp:nuevoArticulo' %}" role="button">Crear nuevo Articulo</a>        
            </div>
            
        </div>
        <div class="col-lg-10">
            {% block contenido%}
            {% endblock %}
        </div>
    </div>
</body>
</html>

exParcial/wikiApp/templates/nuevoArticulo.html
{% extends "layout.html" %}

{% block title %}
    Nuevo Articulo
{% endblock %}


{% block contenido %}
    <h2>Crear nuevo Articulo</h2>
    <form class="row" method="post" action="{% url 'wikiApp:nuevoArticulo' %}" >
        {% csrf_token %}
        <div>
            <label>Titulo</label>
            <input type="text" name="tituloArticulo">
        </div>           
        <div class="input-group">
            <label>Tema</label>
            <select class="custom-select" name="nombreTema" required>
                {% for teaminfo in listaTema %}
                    <option value="{{ teaminfo.id }}">{{ teaminfo.tituloTema }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label>Contenido del articulo</label>
            <textarea class="form-control" name="contenidoArticulo"></textarea>
        </div>
        <div>
            <input type="submit" class="btb btn-success" value="Enviar">
        </div>
    </form>
{% endblock %}

exParcial/wikiApp/templates/nuevoTema.html
{% extends "layout.html" %}

{% block title %}
    Nuevo Tema
{% endblock %}


{% block contenido %}
    <h2>Crear nuevo Tema</h2>
    <form class="row" method="post" action="{% url 'wikiApp:nuevoTema' %}">
        {% csrf_token %}
        <div>
            <label>Ingrese el tema</label>
            <input type="text" name="tituloTema">
        </div>
        <div>
            <label>Ingrese Descripcion</label>
            <input type="text" name="descripcionTema">
        </div>
        <div>
            <input type="submit" value="Enviar">
        </div>
    </form>
{% endblock %}

exParcial/wikiApp/templates/vistaArticulo.html
{% extends "layout.html" %}

{% block title %}
    {{objTema.tituloTema}}
{% endblock %}

{% block contenido %}
        <h1>{{objTema.tituloTema}}</h1>
        <div>
            <h4>{{objTema.descripcionTema}}</h4>
        </div>
        <br>
        {% for teaminfo in listaArticulo %}
            <div>
                <a href="{% url 'wikiApp:vistaDetalleArticulo' teaminfo.id %}">{{ teaminfo.tituloArticulo }}</a>            
            </div>
        {% endfor %}
{% endblock %}

exParcial/wikiApp/templates/vistaDetalleArticulo.html
{% extends "layout.html" %}

{% block title %}
    {{objArticulo.tituloArticulo}}
{% endblock %}

{% block contenido %}
    <h1>{{objArticulo.tituloArticulo}}</h1>
    <div>
        <h4>Contenido : {{objArticulo.contenidoArticulo}}</h4>
    </div>
    <div>
        <h4>Tema : {{objArticulo.temaRelacionado.tituloTema}}</h4>
    </div>


{% endblock %}